import React, { useMemo, useState, useId } from 'react';
import { ArrowUpRight, ArrowDownLeft, Wallet, Users, ChevronRight, Download, TrendingUp, ListTodo, Clock3, Activity, CreditCard, CircleHelp, AlertTriangle } from 'lucide-react';
import { AdminMetrics, AdminWithdrawalItem, AdminDepositItem, AdminUserItem, AdminTabId } from './adminTypes';
import { money, waitLabel, downloadAdminCsv } from './adminUiUtils';
interface Props { metrics: AdminMetrics | null; withdrawals: AdminWithdrawalItem[]; deposits: AdminDepositItem[]; users: AdminUserItem[]; loading: boolean; onNavigate: (tab: AdminTabId) => void; canNavigate: (tab: AdminTabId) => boolean; canExport: boolean; adminName: string; }
export const AdminOverview: React.FC<Props> = ({ metrics, withdrawals, deposits, users, loading, onNavigate, canNavigate, canExport, adminName }) => {
  const [period, setPeriod] = useState<'today' | 'sevenDays' | 'thirtyDays'>('sevenDays');
  const [focusIndex, setFocusIndex] = useState<number | null>(null);
  const [showValues, setShowValues] = useState(true);
  const [showDataTable, setShowDataTable] = useState(false);
  const gradientId = useId().replace(/:/g, '');
  const series = metrics?.chartSeries?.[period] || (period === 'sevenDays' ? metrics?.chartData : []) || [];
  const maxValue = Math.max(1, ...series.flatMap(point => [point.deposits, point.withdrawals]));
  const points = (field: 'deposits' | 'withdrawals') => series.map((point, index) => `${42 + index * (716 / Math.max(1, series.length - 1))},${208 - (point[field] / maxValue) * 168}`).join(' ');
  const totalIn = series.reduce((sum, item) => sum + item.deposits, 0);
  const totalOut = series.reduce((sum, item) => sum + item.withdrawals, 0);
  const pending = useMemo(() => withdrawals.filter(item => item.status === 'pending').sort((a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt)), [withdrawals]);
  const inGateway = pending.filter(item => item.dotfyWithdrawalId || item.gatewayProcessing);
  const ready = pending.filter(item => !item.dotfyWithdrawalId && !item.gatewayProcessing);
  const pendingPix = deposits.filter(item => item.status === 'pending');
  const selectedPoint = focusIndex == null ? null : series[focusIndex];
  const display = (value?: number | null) => !showValues ? '••••••' : money(value);
  const nav = (tab: AdminTabId) => { if (canNavigate(tab)) onNavigate(tab); };
  const userSources = [
    { label: 'Por indicação', count: metrics?.totalReferredUsers ?? 0, color: '#2563eb' },
    { label: 'Orgânicos', count: metrics?.totalOrganicUsers ?? 0, color: '#dce7f5' }
  ];
  const sourceTotal = userSources.reduce((sum, item) => sum + item.count, 0);
  const exportChart = () => downloadAdminCsv(`movimentacao-${period}.csv`, ['Data', 'Depósitos BRL', 'Saques BRL', 'Fluxo BRL'], series.map(item => [item.label || item.date, item.deposits, item.withdrawals, item.deposits - item.withdrawals]));
  return <div className="admin-overview">
    <div className="admin-page-heading"><div><span className="admin-eyebrow">PAINEL DE CONTROLE</span><h1>Visão geral<span className="admin-heading-dot">.</span></h1><p>Olá, {adminName.split(' ')[0] || 'Administrador'}. Acompanhe os números e o que precisa da sua atenção.</p></div><div className="admin-heading-actions"><button className="admin-btn" onClick={() => setShowValues(!showValues)}>{showValues ? 'Ocultar valores' : 'Mostrar valores'}</button>{canNavigate('reports') && <button className="admin-btn" onClick={() => nav('reports')}><Download size={15} />Relatórios</button>}</div></div>
    {!metrics && <div className={`admin-notice ${loading ? '' : 'warning'}`} role="status">{loading ? 'Buscando indicadores da plataforma…' : 'Os indicadores ainda não estão disponíveis. Atualize os dados para tentar novamente.'}</div>}
    <div className="admin-kpi-grid">{[
      { label: 'Depósitos confirmados', value: metrics?.totalDepositsAmount, sub: `${metrics?.totalDepositsCount ?? '—'} depósitos · acumulado`, icon: ArrowDownLeft, target: 'deposits' as AdminTabId },
      { label: 'Resultado dos jogos', value: metrics?.gameGgr, sub: 'Apostas menos prêmios · rodadas encerradas', icon: TrendingUp, target: 'reports' as AdminTabId },
      { label: 'Saques pendentes', value: metrics?.pendingWithdrawalsAmount, sub: `${metrics?.pendingWithdrawalsCount ?? pending.length} solicitações em análise ou processamento`, icon: ArrowUpRight, target: 'operations' as AdminTabId },
      { label: 'Saldo de jogadores', value: metrics?.totalBalance, sub: 'Saldo em carteira · obrigação da plataforma', icon: Wallet, target: 'users' as AdminTabId }
    ].map(item => <button key={item.label} className="admin-kpi" disabled={!canNavigate(item.target)} onClick={() => nav(item.target)}><div className="admin-kpi-top"><span>{item.label}</span><item.icon size={19} /></div><strong aria-busy={loading}>{display(item.value)}</strong><div className="admin-kpi-sub"><span>{item.sub}</span>{canNavigate(item.target) && <ChevronRight size={15} />}</div></button>)}</div>
    <div className="admin-dashboard-grid"><section className="admin-surface admin-flow-panel"><div className="admin-section-heading"><div><h2>Movimentação financeira</h2><p>Entradas confirmadas e saques liquidados por período</p></div><div className="admin-segments">{[{ id: 'today', label: 'Hoje' }, { id: 'sevenDays', label: '7 dias' }, { id: 'thirtyDays', label: '30 dias' }].map(item => <button key={item.id} aria-pressed={period === item.id} className={period === item.id ? 'active' : ''} onClick={() => { setPeriod(item.id as typeof period); setFocusIndex(null); }}>{item.label}</button>)}</div></div>
      <div className="admin-chart-summary"><div><span><i style={{ background: '#2563eb' }} />Entradas</span><strong>{display(totalIn)}</strong></div><div><span><i style={{ background: '#93a4bc' }} />Saídas</span><strong>{display(totalOut)}</strong></div><div><span>Fluxo do período</span><strong className={totalIn - totalOut < 0 ? 'negative' : ''}>{display(totalIn - totalOut)}</strong></div></div>
      {series.length ? <div className="admin-chart" onMouseLeave={() => setFocusIndex(null)}><svg viewBox="0 0 800 240" role="img" aria-label={`Gráfico de depósitos e saques. Entradas: ${money(totalIn)}, saídas: ${money(totalOut)}.`} onMouseMove={event => { const rect = event.currentTarget.getBoundingClientRect(); const x = ((event.clientX - rect.left) / rect.width) * 800; setFocusIndex(Math.min(series.length - 1, Math.max(0, Math.round(((x - 42) / 716) * (series.length - 1))))); }}>
        <defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity=".12" /><stop offset="100%" stopColor="#2563eb" stopOpacity="0" /></linearGradient></defs>
        {[0, 1, 2, 3].map(index => <g key={index}><line x1="42" x2="758" y1={40 + index * 56} y2={40 + index * 56} stroke="#eef1f5" strokeDasharray="4 5" /><text x="0" y={43 + index * 56} fill="#8894a7" fontSize="10">{Math.round(maxValue * (1 - index / 3)).toLocaleString('pt-BR', { notation: 'compact' })}</text></g>)}
        <polygon points={`42,208 ${points('deposits')} 758,208`} fill={`url(#${gradientId})`} /><polyline points={points('withdrawals')} fill="none" stroke="#93a4bc" strokeWidth="2.5" strokeLinejoin="round" /><polyline points={points('deposits')} fill="none" stroke="#2563eb" strokeWidth="3" strokeLinejoin="round" />
        {series.map((item, index) => (index === 0 || index === series.length - 1 || (series.length <= 8 || index % Math.ceil(series.length / 6) === 0)) && <text key={item.date + index} x={42 + index * (716 / Math.max(1, series.length - 1))} y="234" textAnchor="middle" fill="#8894a7" fontSize="10">{item.label || item.date}</text>)}
        {focusIndex != null && <line x1={42 + focusIndex * (716 / Math.max(1, series.length - 1))} x2={42 + focusIndex * (716 / Math.max(1, series.length - 1))} y1="25" y2="208" stroke="#becde1" strokeDasharray="3 3" />}
      </svg>{selectedPoint && <div className="admin-chart-tooltip"><b>{selectedPoint.label || selectedPoint.date}</b><span>Entradas {display(selectedPoint.deposits)}</span><span>Saídas {display(selectedPoint.withdrawals)}</span></div>}</div> : <div className="admin-empty"><Activity size={28} /><strong>Sem série disponível</strong><p>O gráfico aparece quando houver dados para este período.</p></div>}
      <div className="admin-chart-footer"><button className="admin-text-btn" onClick={() => setShowDataTable(!showDataTable)}>{showDataTable ? 'Ocultar tabela' : 'Ver valores em tabela'}</button><span>Valores em BRL</span>{canExport && <button className="admin-text-btn" disabled={!series.length} onClick={exportChart}><Download size={14} />Exportar CSV</button>}</div>
      {showDataTable && <div className="admin-table-wrap"><table className="admin-data-table"><thead><tr><th>Data</th><th>Entradas</th><th>Saídas</th><th>Fluxo</th></tr></thead><tbody>{series.map((item, index) => <tr key={index}><td>{item.label || item.date}</td><td>{display(item.deposits)}</td><td>{display(item.withdrawals)}</td><td>{display(item.deposits - item.withdrawals)}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="admin-surface admin-attention-panel"><div className="admin-section-heading"><div><span className="admin-eyebrow">OPERAÇÃO</span><h2>Precisa de atenção</h2></div><ListTodo size={20} /></div><div className="admin-attention-list">{[
      { label: 'Saques para analisar', count: ready.length, desc: money(ready.reduce((sum, item) => sum + item.amount, 0)), icon: Clock3, tab: 'withdrawals' as AdminTabId },
      { label: 'Aguardando o gateway', count: inGateway.length, desc: 'Enviados ou reservados para conciliação', icon: Activity, tab: 'operations' as AdminTabId },
      { label: 'PIX em aberto', count: pendingPix.length, desc: 'Cobranças ainda sem confirmação', icon: CreditCard, tab: 'deposits' as AdminTabId }
    ].map(item => <button key={item.label} onClick={() => nav(item.tab)} disabled={!canNavigate(item.tab)}><span className="admin-attention-icon"><item.icon size={18} /></span><span><strong>{item.label}</strong><small>{item.desc}</small></span><b>{item.count}</b><ChevronRight size={14} /></button>)}</div>{pending[0] && <div className="admin-queue-age"><Clock3 size={14} /><span>Solicitação mais antiga: <strong>{waitLabel(pending[0].createdAt)}</strong></span></div>}<div className="admin-small-note"><CircleHelp size={15} /><p>Envio ao gateway e confirmação bancária são etapas diferentes.</p></div>{canNavigate('operations') && <button className="admin-btn admin-btn-primary w-full" onClick={() => nav('operations')}>Abrir central de pendências <ArrowUpRight size={15} /></button>}</section></div>
    <div className="admin-dashboard-bottom"><section className="admin-surface"><div className="admin-section-heading"><div><h2>Atividade recente</h2><p>Últimos eventos registrados na plataforma</p></div><span className="admin-soft-badge">{metrics?.recentActivities?.length || 0} eventos</span></div>{metrics?.recentActivities?.length ? <div className="admin-activity-list">{metrics.recentActivities.slice(0, 6).map(item => <div key={item.id}><span className={`admin-activity-icon ${item.type === 'withdrawal' ? 'outgoing' : ''}`}>{item.type === 'user_registered' ? <Users size={17} /> : item.type === 'withdrawal' ? <ArrowUpRight size={17} /> : <ArrowDownLeft size={17} />}</span><span><strong>{item.title}</strong><small>{item.userName}</small></span><span className="admin-activity-amount"><b>{item.amount == null ? 'Nova conta' : display(item.amount)}</b><small>{item.timeAgo}</small></span></div>)}</div> : <div className="admin-empty"><Activity size={24} /><p>Nenhuma atividade disponível.</p></div>}</section>
      <section className="admin-surface"><div className="admin-section-heading"><div><h2>Base de usuários</h2><p>Origem dos cadastros · acumulado</p></div><Users size={19} /></div><div className="admin-audience"><div className="admin-donut" style={{ background: sourceTotal ? `conic-gradient(#2563eb ${userSources[0].count / sourceTotal * 360}deg, #e4ebf5 0deg)` : '#eef2f7' }}><div><strong>{metrics?.totalUsers?.toLocaleString('pt-BR') ?? '—'}</strong><small>usuários</small></div></div><div>{userSources.map(item => <div className="admin-audience-line" key={item.label}><span><i style={{ background: item.color }} />{item.label}</span><strong>{metrics ? item.count.toLocaleString('pt-BR') : '—'}</strong></div>)}<div className="admin-audience-line"><span>Novos hoje</span><strong>{metrics?.newUsersToday ?? '—'}</strong></div></div></div><div className="admin-small-note"><Wallet size={15} /><p>Comissões em carteira: <strong>{display(metrics?.totalAffiliateBalance)}</strong></p></div>{canNavigate('users') && <button className="admin-text-btn" onClick={() => nav('users')}>Gerenciar usuários e afiliados <ChevronRight size={14} /></button>}</section>
    </div><p className="admin-finance-footnote"><AlertTriangle size={13} />O resultado dos jogos não inclui todos os custos, taxas e tributos. Depósitos representam entradas de caixa.</p>
  </div>;
};
