import React, { useEffect, useState } from 'react';
import { Users, BarChart3, Activity, Link2, Calculator, SlidersHorizontal, ArrowRight, Copy, Check, QrCode, Search, Download, Bell, ChevronRight, Wallet, DollarSign, Layers } from 'lucide-react';
import { PartnerAffiliateStats, PartnerDashboardData } from '../../types';
import type { PartnerTabType } from './PartnerMobileTabBar';
import { money, downloadAdminCsv } from '../admin/adminUiUtils';
export const partnerTabs: Array<{id: PartnerTabType;label:string;icon:typeof Users;group:string}> = [
  {id:'overview',label:'Visão geral',icon:BarChart3,group:'Sua rede'}, {id:'affiliates',label:'Afiliados',icon:Users,group:'Sua rede'}, {id:'reports',label:'Relatórios',icon:BarChart3,group:'Sua rede'}, {id:'recruiting',label:'Links e materiais',icon:Link2,group:'Ferramentas'}, {id:'ranking',label:'Ranking',icon:BarChart3,group:'Ferramentas'}, {id:'realtime',label:'Atividade',icon:Activity,group:'Ferramentas'}, {id:'simulator',label:'Simulador',icon:Calculator,group:'Ferramentas'}, {id:'diversion',label:'Regras de PIX',icon:SlidersHorizontal,group:'Configuração'}
];
export function PartnerNavigation({activeTab,onSelectTab}: {activeTab:PartnerTabType;onSelectTab:(tab:PartnerTabType)=>void}) {
  return <nav className="pc-navigation" aria-label="Navegação de parceiros">{['Sua rede','Ferramentas','Configuração'].map(group=><div key={group}><p>{group}</p>{partnerTabs.filter(tab=>tab.group===group).map(tab=><button key={tab.id} aria-current={activeTab===tab.id?'page':undefined} onClick={()=>onSelectTab(tab.id)} className={activeTab===tab.id?'active':''}><tab.icon size={17}/>{tab.label}</button>)}</div>)}</nav>;
}
function Stat({label,value,hint,icon:Icon}: {label:string;value:string|number;hint:string;icon:typeof Users}) {return <article className="pc-stat"><div><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small>{hint}</small></article>}
export function PartnerCleanOverview({data,link,copied,onCopy,onNavigate,onQr,onDetail}: {data:PartnerDashboardData;link:string;copied:boolean;onCopy:()=>void;onNavigate:(tab:PartnerTabType)=>void;onQr:()=>void;onDetail:(affiliate:PartnerAffiliateStats)=>void}) {
 const m=data.metrics;
 return <div className="pc-overview"><div className="pc-heading"><div><span>VISÃO GERAL</span><h1>Sua rede, em um só lugar.</h1><p>Acompanhe os resultados e acesse o que precisa.</p></div><button className="pc-button pc-primary" onClick={()=>onNavigate('affiliates')}>Ver afiliados<ArrowRight size={15}/></button></div>
 <div className="pc-stats"><Stat label="Comissões acumuladas" value={money(m.totalPartnerCommissions)} hint="Repasses registrados no histórico" icon={Wallet}/><Stat label="Depósitos da rede" value={money(m.totalDepositedByNetwork)} hint={`${m.ftdCount} primeiros depositantes`} icon={DollarSign}/><Stat label="Afiliados na rede" value={m.totalAffiliates} hint={`${m.activeAffiliatesToday} com atividade hoje`} icon={Users}/><Stat label="Jogadores indicados" value={m.totalPlayersInNetwork} hint={`${m.realtimeActivePlayers} ativos agora`} icon={Layers}/></div>
 <div className="pc-overview-grid"><section className="pc-card pc-invite"><div><span className="pc-soft-icon"><Link2 size={20}/></span><h2>Convide novos afiliados</h2><p>Compartilhe seu link de cadastro para ampliar sua rede.</p></div><label htmlFor="partner-invite">Seu link de convite</label><div className="pc-link"><input id="partner-invite" readOnly value={link} onFocus={e=>e.target.select()} /><button className="pc-button pc-primary" disabled={!link} onClick={onCopy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copiado':'Copiar link'}</button></div><div className="pc-inline"><button className="pc-button" onClick={onQr} disabled={!link}><QrCode size={15}/>QR Code</button><button className="pc-text-button" onClick={()=>onNavigate('recruiting')}>Ver links e materiais<ArrowRight size={14}/></button></div></section>
 <section className="pc-card pc-network"><h2>Resumo da rede</h2><dl><div><dt>Conversão em depositantes</dt><dd>{Number(m.conversionRate || 0).toLocaleString('pt-BR')}%</dd></div><div><dt>Resultado dos jogos (GGR)</dt><dd>{money(m.ggr)}</dd></div><div><dt>Saques automáticos bloqueados</dt><dd>{m.blockedWithdrawalsCount}</dd></div></dl><p>Indicadores da rede. O total de comissões não representa o saldo disponível para saque.</p><button className="pc-text-button" onClick={()=>onNavigate('reports')}>Abrir relatórios<ArrowRight size={14}/></button></section></div>
 <section className="pc-card"><div className="pc-card-title"><div><h2>Afiliados recentes</h2><p>Últimos cadastros vinculados à sua rede.</p></div><button className="pc-text-button" onClick={()=>onNavigate('affiliates')}>Ver todos<ArrowRight size={14}/></button></div><div className="pc-recent">{[...data.affiliates].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,4).map(a=><button key={a.id} onClick={()=>onDetail(a)}><span className="pc-avatar">{a.name?.charAt(0)||'A'}</span><span><strong>{a.name}</strong><small>{a.totalPlayersInvited} jogadores indicados</small></span><ChevronRight size={16}/></button>)}{!data.affiliates.length&&<p className="pc-empty">Sua rede ainda não tem afiliados. Comece compartilhando seu link.</p>}</div></section></div>;
}
type Props={affiliates:PartnerAffiliateStats[];total:number;search:string;onSearch:(q:string)=>void;status:'all'|'active'|'blocked'|'idle';onStatus:(s:Props['status'])=>void;sort:string;onSort:(s:any)=>void;advanced:boolean;onAdvanced:()=>void;revShare:string;onRevShare:(s:any)=>void;onReset:()=>void;onDetail:(a:PartnerAffiliateStats)=>void;onBroadcast:()=>void};
export function PartnerCleanAffiliates(p:Props){const [limit,setLimit]=useState(20);useEffect(()=>setLimit(20),[p.search,p.status,p.sort,p.revShare]);const rows=p.affiliates.slice(0,limit);
 const exportFiltered=()=>downloadAdminCsv('afiliados-filtrados.csv',['Nome','Email','Código','Jogadores','Depósitos BRL','Comissão BRL','Saque automático'],p.affiliates.map(a=>[a.name,a.email,a.referralCode,a.totalPlayersInvited,a.totalDeposited,a.commissionGeneratedForPartner,a.autoWithdrawBlocked?'Bloqueado':'Liberado']));
 return <div><div className="pc-heading"><div><span>SUA REDE</span><h1>Afiliados</h1><p>Confira os resultados e gerencie cada afiliado pelos detalhes.</p></div><button className="pc-button" onClick={p.onBroadcast}><Bell size={15}/>Enviar comunicado</button></div><section className="pc-card"><div className="pc-list-toolbar"><div className="pc-search"><Search size={16}/><input aria-label="Buscar afiliados" placeholder="Nome, e-mail ou código" value={p.search} onChange={e=>p.onSearch(e.target.value)}/></div><select aria-label="Filtrar afiliados" value={p.status} onChange={e=>p.onStatus(e.target.value as Props['status'])}><option value="all">Todos os afiliados</option><option value="active">Online agora</option><option value="idle">Offline agora</option><option value="blocked">Saque bloqueado</option></select><button className={`pc-button ${p.advanced?'pc-selected':''}`} aria-expanded={p.advanced} onClick={p.onAdvanced}><SlidersHorizontal size={15}/>Filtros</button><button className="pc-button" disabled={!p.affiliates.length} onClick={exportFiltered}><Download size={15}/>Exportar</button></div>{p.advanced&&<div className="pc-advanced"><label>Ordenar por<select value={p.sort} onChange={e=>p.onSort(e.target.value)}><option value="deposits_desc">Maior volume de depósitos</option><option value="commission_desc">Maior comissão</option><option value="players_desc">Mais jogadores</option><option value="name_asc">Nome A–Z</option><option value="recent">Cadastro recente</option></select></label><label>Comissão do afiliado<select value={p.revShare} onChange={e=>p.onRevShare(e.target.value)}><option value="all">Todas</option>{[80,75,70,65].map(n=><option key={n} value={n}>{n}%</option>)}</select></label><button className="pc-text-button" onClick={p.onReset}>Limpar filtros</button></div>}
 <div className="pc-table-wrap"><table className="pc-affiliate-table"><thead><tr><th>Afiliado</th><th>Jogadores</th><th>Depósitos</th><th>Comissão gerada</th><th>Saque automático</th><th></th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><div className="pc-person"><span className="pc-avatar">{a.name?.charAt(0)||'A'}</span><div><strong>{a.name}</strong><small>{a.email}</small></div></div></td><td>{a.totalPlayersInvited}</td><td>{money(a.totalDeposited)}</td><td>{money(a.commissionGeneratedForPartner)}</td><td><span className={`pc-badge ${a.autoWithdrawBlocked?'warning':''}`}>{a.autoWithdrawBlocked?'Bloqueado':'Liberado'}</span></td><td><button className="pc-button" aria-label={`Ver detalhes de ${a.name}`} onClick={()=>p.onDetail(a)}>Detalhes<ChevronRight size={14}/></button></td></tr>)}</tbody></table></div>
 <div className="pc-affiliate-cards">{rows.map(a=><button key={a.id} aria-label={`Ver detalhes de ${a.name}`} className="pc-affiliate-card" onClick={()=>p.onDetail(a)}><div className="pc-person"><span className="pc-avatar">{a.name?.charAt(0)||'A'}</span><div><strong>{a.name}</strong><small>{a.email}</small></div><ChevronRight size={16}/></div><div className="pc-card-metrics"><span>Depósitos<strong>{money(a.totalDeposited)}</strong></span><span>Comissão<strong>{money(a.commissionGeneratedForPartner)}</strong></span></div><div className="pc-inline"><small>{a.totalPlayersInvited} jogadores</small><span className={`pc-badge ${a.autoWithdrawBlocked?'warning':''}`}>Saque {a.autoWithdrawBlocked?'bloqueado':'liberado'}</span></div></button>)}</div>
 {!rows.length&&<div className="pc-empty"><Users size={24}/><strong>{p.total?'Nenhum afiliado encontrado':'Sua rede ainda está vazia'}</strong><p>{p.total?'Ajuste a busca ou limpe os filtros.':'Compartilhe seu link para convidar afiliados.'}</p>{p.total>0&&<button className="pc-button" onClick={p.onReset}>Limpar filtros</button>}</div>}<div className="pc-list-footer"><span>{Math.min(limit,p.affiliates.length)} de {p.affiliates.length} afiliados · {p.total} na rede</span>{limit<p.affiliates.length&&<button className="pc-button" onClick={()=>setLimit(n=>n+20)}>Mostrar mais 20</button>}</div></section></div>;
}
